imporve build system

diff --git a/.github/workflows/linux_run.yml b/.github/workflows/linux_run.yml
--- a/.github/workflows/linux_run.yml
+++ b/.github/workflows/linux_run.yml
@@ -22,7 +22,18 @@ jobs:
     runs-on: ${{ inputs.runner }} # Dynamically use input
 
     env:
+      COMPILER: ${{ inputs.compiler }}
+      RUNNER: ${{ inputs.runner }}
       BUILD_TYPE: Debug
+      WORKSPACE: ${{ github.workspace }}
+      BUILD_DIR: build
+      BUILD_RELEASE_DIR: build-release
+      GCC_DEBUG_PRESET: linux-debug-GNU
+      CLANG_DEBUG_PRESET: linux-debug-clang
+      GCC_PROFILE_PRESET: linux-profile-GNU
+      CLANG_PROFILE_PRESET: linux-profile-clang
+      CLANG_RELEASE_PRESET: linux-release-clang
+      COVERAGE_JSON: coverage.json
 
     steps:
       - uses: actions/checkout@v5.0.0
@@ -30,120 +41,137 @@ jobs:
           fetch-depth: 0
           submodules: recursive
 
+      #################################################################################################################
+      ######################################## Prepare deps ###########################################################
+      #################################################################################################################
       - name: Install dependencies
         run: |
-          sudo apt-get install -y llvm
-          chmod +x scripts/linux/setup_dependencies.sh
-          ./scripts/linux/setup_dependencies.sh
-
-      - name: Install gcovr
-        run: |
-          gcov --version || true
-          which gcov || true
-          pip install gcovr
-
-      - name: Install latest CMake
-        run: |
-          sudo apt-get purge --auto-remove -y cmake
-          sudo apt-get update
-          sudo apt-get install -y wget gpg lsb-release ca-certificates
-          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc \
-            | gpg --dearmor \
-            | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
-          echo "deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ noble main" \
-            | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
-          sudo apt-get update
-          sudo apt-get install -y cmake
+          chmod +x scripts/linux/setup-dependencies.sh
+          ./scripts/linux/setup-dependencies.sh
           echo "/usr/bin" >> $GITHUB_PATH
-          cmake --version
 
-      - name: Configure CMake
+      #################################################################################################################
+      ############################## Run unit/integration/fuzzy/coverage/tests/static analyzers #######################
+      #################################################################################################################
+      - name: Configure/build CMake for Debug (select preset by compiler)
         run: |
-          if [[ "${{ inputs.compiler }}" == "gcc" ]]; then
-            cmake -B build --preset "linux-profile-GNU"
+          if [[ "${COMPILER}" == "gcc" ]]; then
+            PRESET="${GCC_DEBUG_PRESET}"
           else
-            cmake -B build --preset "linux-profile-clang"
+            PRESET="${CLANG_DEBUG_PRESET}"
           fi
+          echo "Using preset: ${PRESET}"
+          cmake -B "${WORKSPACE}/${BUILD_DIR}" --preset "${PRESET}"
+          cmake --build "${WORKSPACE}/${BUILD_DIR}" --preset "${PRESET}"
 
-      - name: Build
+      - name: Run Unit/Integration tests
+        working-directory: ${{ github.workspace }}/$BUILD_DIR
         run: |
-          export CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)
-          cmake --build build --config $BUILD_TYPE
-
-      - name: Test
-        working-directory: build
-        run: |
-          ctest -C $BUILD_TYPE
-          if [[ "${{ inputs.compiler }}" == "gcc" ]]; then
-            gcovr -r .
-          else
-            /usr/bin/llvm-profdata merge -sparse Test/compile/default.profraw -o compileTestSuite.profdata
-            /usr/bin/llvm-cov report ./compileTestSuite -instr-profile=compileTestSuite.profdata
-            /usr/bin/llvm-cov export ./compileTestSuite -format=text -instr-profile=compileTestSuite.profdata > coverage.json
-          fi
-
-      - name: Run performance benchmarks
-        run: ./build/perfTestSuite
-
-      - name: Run GProf
-        run: |
-          cd build
-          ./KataglyphisCppProject
-          gprof KataglyphisCppProject gmon.out > profile.txt
+          ctest -C $BUILD_TYPE --verbose --extra-verbose --debug -T test --output-on-failure
 
       - name: Run fuzzer tests
         run: |
           if [[ "${{ inputs.compiler }}" == "clang" ]]; then
-            ./build/first_fuzz_test
+            ./${{ env.BUILD_DIR }}/first_fuzz_test
           else
             echo "Compiled with GCC so no fuzz testing!"
+          fi  
+
+      - name: Build Code Coverage
+        run: |
+          if [[ "${{ inputs.compiler }}" == "gcc" ]]; then
+            gcovr -r .
+          else
+            llvm-profdata merge -sparse Test/compile/default.profraw -o compileTestSuite.profdata
+            llvm-cov report ./compileTestSuite -instr-profile=compileTestSuite.profdata
+            llvm-cov export ./compileTestSuite -format=text -instr-profile=compileTestSuite.profdata > ${{ env.COVERAGE_JSON }}
+            llvm-cov show ./compileTestSuite -instr-profile=compileTestSuite.profdata
           fi
 
+      - name: Codecov
+        if: ${{ inputs.compiler == 'clang' && inputs.runner == 'ubuntu-24.04' }}
+        uses: codecov/codecov-action@v5.5.1
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
+          files: ${{ env.COVERAGE_JSON }}
+          name: codecov-umbrella
+          fail_ci_if_error: false
+          verbose: false
+
       - name: Run clang tidy
-        run: clang-tidy -p=./build/compile_commands.json  $(find Src -name '*.cpp' -o -name '*.cc')
+        run: clang-tidy -p=./${{ env.BUILD_DIR }}/compile_commands.json  $(find Src -name '*.cpp' -o -name '*.cc')
 
-      ####################################
-      ###### Now run everything with clang
-      ####################################
-
-      - name: Prepare for clang
+      - name: Run Clang static analysis (HTML)
+        if: ${{ inputs.compiler == 'clang' }}
         run: |
-          sudo rm -r ${{github.workspace}}/build
-          which clang 
-          clang --version
+          # HTML output (correct flag form)
+          clang++ --analyze -Xanalyzer -analyzer-output=html $(find Src -name '*.cpp' -o -name '*.cc')
 
-      - name: Configure CMake with Clang
-        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
-        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
-        run: cmake -B ${{github.workspace}}/build --preset "linux-profile-clang"
-
-      - name: Build
-        # Build your program with the given configuration
+      - name: Run Clang static analysis (scan-build)
+        if: ${{ inputs.compiler == 'clang' }}
         run: |
-          export CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)   # Linux: number of cores
-          # for running a CICD Job enabling cache would be a foolish thing to do
-          cmake --build ${{github.workspace}}/build --preset "linux-profile-clang"
+          mkdir -p scan-build-reports
+          scan-build -o scan-build-reports cmake --build "${WORKSPACE}/${BUILD_DIR}" --preset "${CLANG_DEBUG_PRESET}"
 
-      - name: Test
-        working-directory: ${{github.workspace}}/build
-        # Execute tests defined by the CMake configuration.
-        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
+      #################################################################################################################
+      ############################# Now run on performance benchmarking/profiling #####################################
+      #################################################################################################################
+      - name: Configure/build CMake for Profiling (select preset by compiler)
         run: |
-          ctest -C ${{env.BUILD_TYPE}}
-          /usr/bin/llvm-profdata merge -sparse ${{github.workspace}}/build/Test/compile/default.profraw -o ${{github.workspace}}/build/compileTestSuite.profdata
-          /usr/bin/llvm-cov report ${{github.workspace}}/build/compileTestSuite -instr-profile=${{github.workspace}}/build/compileTestSuite.profdata
-          /usr/bin/llvm-cov export ${{github.workspace}}/build/compileTestSuite -format=text -instr-profile=${{github.workspace}}/build/compileTestSuite.profdata > ${{github.workspace}}/build/coverage.json
+          if [[ "${COMPILER}" == "gcc" ]]; then
+            PRESET="${GCC_PROFILE_PRESET}"
+          else
+            PRESET="${CLANG_PROFILE_PRESET}"
+          fi
+          echo "Using preset: ${PRESET}"
+          cmake -B "${WORKSPACE}/${BUILD_DIR}" --preset "${PRESET}"
+          cmake --build "${WORKSPACE}/${BUILD_DIR}" --preset "${PRESET}"
 
+      - name: Run Instrumentation-based PGO Clang/LLVM
+        run: |
+          cd build
+          LLVM_PROFILE_FILE="dummy.profraw" ./KataglyphisCppProject
+          llvm-profdata merge -sparse dummy.profraw -o dummy.profdata
+          llvm-cov show ./KataglyphisCppProject -instr-profile=dummy.profdata -format=text
+      
+      - name: Run Callgrind measurements
+        run: |
+          valgrind --tool=callgrind ./KataglyphisCppProject
+
+      - name: Run Perf measurements
+        run: |
+          perf record -F 99 --call-graph dwarf -- ./KataglyphisCppProject
+
+      - name: Run performance benchmarks
+        run: ./${{ env.BUILD_DIR }}/perfTestSuite
+
+      - name: Run GProf
+        run: |
+          cd "${WORKSPACE}/${BUILD_DIR}"
+          ./KataglyphisCppProject
+          if [[ -f gmon.out ]]; then
+            gprof KataglyphisCppProject gmon.out > profile.txt || true
+          else
+            echo "gmon.out not found, skipping gprof."
+          fi
+
+      #################################################################################################################
+      ######################################## Build docs #############################################################
+      #################################################################################################################
       - name: Set up Python 3.13
+        if: ${{ inputs.runner == 'ubuntu-24.04' && inputs.compiler == 'clang' }}
         uses: actions/setup-python@v6.0.0
         with:
           python-version: "3.13"
+
       # You can test your matrix by printing the current Python version
       - name: Setup python env
+        if: ${{ inputs.runner == 'ubuntu-24.04' && inputs.compiler == 'clang' }}
         run: |
           pip install -r requirements.txt
 
       - name: Build web page
+        if: ${{ inputs.runner == 'ubuntu-24.04' && inputs.compiler == 'clang' }}
         run: |
           cd docs
           make html
@@ -157,28 +185,19 @@ jobs:
           password: ${{ secrets.PW }}
           local-dir: "./docs/build/html/"
 
-      - name: Run performance benchmarks
-        run: |
-          # chmod +x ${{github.workspace}}/build/perfTestSuite 
-          ${{github.workspace}}/build/perfTestSuite
+      #################################################################################################################
+      ################################### Now run release and build package for clang #################################
+      #################################################################################################################
 
-      - name: Run LLVM Source based Code Coverage
+      - name: Prepare for clang release
         run: |
-          cd build
-          LLVM_PROFILE_FILE="dummy.profraw" ./KataglyphisCppProject
-          /usr/bin/llvm-profdata merge -sparse dummy.profraw -o dummy.profdata
-          /usr/bin/llvm-cov show ./KataglyphisCppProject -instr-profile=dummy.profdata -format=text
+          sudo rm -r "${WORKSPACE}/${BUILD_DIR}"
 
-      - name: Configure CMake for Release (Clang only)
+      - name: Configure CMake with Clang
         if: ${{ inputs.compiler == 'clang' }}
         run: |
-          cmake -B build-release --preset linux-release-clang
-
-      - name: Build Release (Clang only)
-        if: ${{ inputs.compiler == 'clang' }}
-        run: |
-          export CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)
-          cmake --build build-release --config linux-release-clang
+          cmake -B "${WORKSPACE}/${BUILD_DIR}" --preset "${CLANG_RELEASE_PRESET}"
+          cmake --build "${WORKSPACE}/${BUILD_DIR}" --preset "${CLANG_RELEASE_PRESET}"
 
       - name: Package (Clang only)
         if: ${{ inputs.compiler == 'clang' }}
